# Generated by Django 4.1.3 on 2022-12-13 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Answer description', max_length=100, verbose_name='description')),
                ('is_correct', models.BooleanField(help_text='Is answer correct?', verbose_name='is_correct')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Question description', max_length=1000, verbose_name='content')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Question type', max_length=50, unique=True, verbose_name='name')),
                ('description', models.CharField(blank=True, help_text='Question type description', max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Question type',
                'verbose_name_plural': 'Question types',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Session key', max_length=40, verbose_name='session_key')),
                ('is_completed', models.BooleanField(default=False, help_text='Is quiz completed?', verbose_name='is_completed')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Quiz total score', verbose_name='score')),
                ('questions', models.ManyToManyField(help_text='Quiz questions', related_name='quizes', to='questions.question', verbose_name='questions')),
                ('user', models.ForeignKey(help_text='User having quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizes',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='QuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Question collection name', max_length=100, verbose_name='name')),
                ('description', models.CharField(help_text='Question collection description', max_length=200, verbose_name='description')),
                ('collection_questions', models.ManyToManyField(help_text='Questions in qeustion collection', related_name='collections', to='questions.question', verbose_name='collection_questions')),
            ],
            options={
                'verbose_name': 'Question Collection',
                'verbose_name_plural': 'Question Collections',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(help_text='Question type', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questiontype', verbose_name='question_type'),
        ),
        migrations.CreateModel(
            name='AnswerGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(help_text='Answer given by user', on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='answer')),
                ('question', models.ForeignKey(help_text='Answer related question', on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to='questions.question')),
                ('quiz', models.ForeignKey(help_text='Related quiz', on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to='questions.quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'Answer given',
                'verbose_name_plural': 'Answers given',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(help_text='Related question', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='question'),
        ),
    ]
