# Generated by Django 4.1.3 on 2022-12-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_passed', models.BooleanField(default=False, help_text='Is quiz passed?', verbose_name='is_passed')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Quiz total score', verbose_name='score')),
                ('questions', models.ManyToManyField(help_text='Quiz questions', related_name='quizes', to='questions.question', verbose_name='questions')),
                ('user', models.ForeignKey(help_text='User havig quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerGiven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text='Is given answer correct?', verbose_name='is_correct')),
                ('description', models.CharField(help_text='Answer description', max_length=100, verbose_name='description')),
                ('question', models.ForeignKey(help_text='Answer related question', on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to='questions.question')),
                ('quiz', models.ForeignKey(help_text='Related quiz', on_delete=django.db.models.deletion.CASCADE, related_name='answers_given', to='questions.quiz', verbose_name='quiz')),
            ],
        ),
    ]
