# Generated by Django 4.1.3 on 2022-12-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_quiz_answergiven'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-pk',), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='answergiven',
            options={'ordering': ('-pk',), 'verbose_name': 'AnswerGiven', 'verbose_name_plural': 'AnswersGiven'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-pk',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'ordering': ('-pk',), 'verbose_name': 'Question type', 'verbose_name_plural': 'Question types'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-pk',), 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='session_key',
            field=models.CharField(default=0, help_text='Session key', max_length=40, verbose_name='session_key'),
            preserve_default=False,
        ),
    ]
