# Generated by Django 4.1.3 on 2022-12-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answer_options_alter_answergiven_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answergiven',
            name='description',
        ),
        migrations.RemoveField(
            model_name='answergiven',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answergiven',
            name='answer',
            field=models.ForeignKey(default=1, help_text='Answer given by user', on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='answer'),
            preserve_default=False,
        ),
    ]
