# Generated by Django 4.1.3 on 2022-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_is_passed_quiz_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Is quiz completed?', verbose_name='is_completed'),
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Question set name', max_length=100, verbose_name='name')),
                ('description', models.CharField(help_text='Question set description', max_length=200, verbose_name='description')),
                ('questions', models.ManyToManyField(help_text='Questions in qeustion set', related_name='question_sets', to='questions.question', verbose_name='questions')),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
                'ordering': ('-pk',),
            },
        ),
    ]
