# Generated by Django 4.1.3 on 2022-12-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_quiz_is_completed_questionset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answergiven',
            options={'ordering': ('-pk',), 'verbose_name': 'Answer given', 'verbose_name_plural': 'Answers given'},
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='questions',
        ),
        migrations.AddField(
            model_name='questionset',
            name='set_questions',
            field=models.ManyToManyField(help_text='Questions in qeustion set', related_name='question_set_sets', to='questions.question', verbose_name='questions'),
        ),
    ]
