# Generated by Django 4.1.3 on 2022-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_questionset_set_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Question set name', max_length=100, verbose_name='name')),
                ('description', models.CharField(help_text='Question set description', max_length=200, verbose_name='description')),
                ('collection_questions', models.ManyToManyField(help_text='Questions in qeustion collection', related_name='question_collections', to='questions.question', verbose_name='collection_questions')),
            ],
            options={
                'verbose_name': 'Question Set',
                'verbose_name_plural': 'Question Sets',
                'ordering': ('-pk',),
            },
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
