# Generated by Django 4.1.3 on 2022-12-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questioncollection_delete_questionset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncollection',
            options={'ordering': ('-pk',), 'verbose_name': 'Question Collection', 'verbose_name_plural': 'Question Collections'},
        ),
    ]
