# Generated by Django 4.1.3 on 2022-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_questioncollection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncollection',
            name='collection_questions',
            field=models.ManyToManyField(help_text='Questions in qeustion collection', related_name='collections', to='questions.question', verbose_name='collection_questions'),
        ),
        migrations.AlterField(
            model_name='questioncollection',
            name='description',
            field=models.CharField(help_text='Question collection description', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='questioncollection',
            name='name',
            field=models.CharField(help_text='Question collection name', max_length=100, verbose_name='name'),
        ),
    ]
